# Build the image from the current Dockerfile

matrix:
  PLATFORM:
    - linux/amd64
  TARGET_ENV:
    - webdev
    - bwdev
    - production
  NODE_VERSION:
    - 18

when:
  event: push
  branch: [master, next, "#ci"]

platform: ${PLATFORM}

pipeline:
  - name: build ${TARGET_ENV} ${CI_COMMIT_BRANCH}
    image: docker:latest
    # Shared host Docker socket
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build --build-arg env=${TARGET_ENV} -t geo2-frontend:${TARGET_ENV}-${CI_COMMIT_BRANCH###} .
  # share-images: TODO registry
